import PDFDocument from 'pdfkit';
import type { PostGameReportContent } from '../../types';

const COLOR_HEADER = '#1e3a5f';
const COLOR_BODY = '#1a1a1a';
const COLOR_MUTED = '#6b7280';
const COLOR_BORDER = '#e2e8f0';

export function buildPostGameReportPdf(content: PostGameReportContent): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: 'LETTER', margin: 48, info: { Title: `Postgame Report — ${content.game_label}` } });
            const chunks: Buffer[] = [];
            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            renderHeader(doc, content);
            if (content.narrative) renderNarrative(doc, content.narrative);
            renderOutcomeTotals(doc, content.outcome_totals);
            if (content.pitch_mix.length > 0) renderPitchMix(doc, content.pitch_mix);
            if (content.per_pitcher.length > 0) renderPerPitcher(doc, content.per_pitcher);
            if (content.per_hitter.length > 0) renderPerHitter(doc, content.per_hitter);
            renderFooter(doc, content.generated_at);

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
}

function renderHeader(doc: PDFKit.PDFDocument, content: PostGameReportContent): void {
    doc.fillColor(COLOR_HEADER).fontSize(20).font('Helvetica-Bold').text('Pitch Chart — Postgame Report');
    doc.moveDown(0.3);
    doc.fillColor(COLOR_BODY).fontSize(13).font('Helvetica').text(content.game_label);
    doc.moveDown(0.8);
    drawDivider(doc);
    doc.moveDown(0.6);
}

function renderNarrative(doc: PDFKit.PDFDocument, narrative: string): void {
    sectionHeading(doc, 'Coaching summary');
    doc.fillColor(COLOR_BODY).fontSize(11).font('Helvetica-Oblique').text(narrative, { align: 'left', lineGap: 2 });
    doc.moveDown(0.8);
}

function renderOutcomeTotals(doc: PDFKit.PDFDocument, totals: PostGameReportContent['outcome_totals']): void {
    sectionHeading(doc, 'Our hitters');
    const ipOuts = totals.weak_contact_outs + totals.hard_contact_outs;
    const cells: Array<[string, number]> = [
        ['Hits', totals.hits],
        ['Walks', totals.walks],
        ['Strikeouts', totals.strikeouts],
        ['In-play outs', ipOuts],
    ];
    const startX = doc.x;
    const y = doc.y;
    const cellW = (doc.page.width - doc.page.margins.left - doc.page.margins.right) / cells.length;
    cells.forEach(([label, value], i) => {
        const x = startX + i * cellW;
        doc.fillColor(COLOR_HEADER)
            .fontSize(20)
            .font('Helvetica-Bold')
            .text(String(value), x, y, { width: cellW, align: 'center' });
        doc.fillColor(COLOR_MUTED)
            .fontSize(9)
            .font('Helvetica')
            .text(label.toUpperCase(), x, y + 26, { width: cellW, align: 'center' });
    });
    doc.x = startX;
    doc.y = y + 50;
}

function renderPitchMix(doc: PDFKit.PDFDocument, mix: PostGameReportContent['pitch_mix']): void {
    sectionHeading(doc, 'Opponent pitch mix');
    drawTable(
        doc,
        ['Pitch type', '%'],
        mix.slice(0, 5).map((m) => [m.pitch_type, `${m.pct}%`]),
        [0.7, 0.3]
    );
}

function renderPerPitcher(doc: PDFKit.PDFDocument, rows: PostGameReportContent['per_pitcher']): void {
    sectionHeading(doc, 'Our pitchers');
    drawTable(
        doc,
        ['Pitcher', 'P', 'Strike%', 'H', 'R'],
        rows.map((r) => [
            r.pitcher_name,
            String(r.total_pitches),
            `${r.strike_percentage}%`,
            r.hits_allowed != null ? String(r.hits_allowed) : '—',
            r.runs_allowed != null ? String(r.runs_allowed) : '—',
        ]),
        [0.44, 0.12, 0.18, 0.13, 0.13]
    );
}

function renderPerHitter(doc: PDFKit.PDFDocument, rows: PostGameReportContent['per_hitter']): void {
    sectionHeading(doc, 'Per-hitter (top of order)');
    drawTable(
        doc,
        ['#', 'Hitter', 'PA', 'H', 'BB', 'K'],
        rows.map((r) => [
            String(r.batting_order),
            r.batter_name,
            String(r.at_bats_count),
            String(r.hits),
            String(r.walks),
            String(r.strikeouts),
        ]),
        [0.08, 0.5, 0.105, 0.105, 0.105, 0.105]
    );
}

function renderFooter(doc: PDFKit.PDFDocument, generatedAt: string): void {
    doc.moveDown(1.2);
    drawDivider(doc);
    doc.moveDown(0.4);
    doc.fillColor(COLOR_MUTED)
        .fontSize(9)
        .font('Helvetica')
        .text(`Generated by Pitch Chart on ${generatedAt}`, { align: 'center' });
}

function sectionHeading(doc: PDFKit.PDFDocument, label: string): void {
    doc.fillColor(COLOR_MUTED).fontSize(10).font('Helvetica-Bold').text(label.toUpperCase(), { characterSpacing: 0.6 });
    doc.moveDown(0.3);
}

function drawDivider(doc: PDFKit.PDFDocument): void {
    const left = doc.page.margins.left;
    const right = doc.page.width - doc.page.margins.right;
    doc.strokeColor(COLOR_BORDER).lineWidth(0.5).moveTo(left, doc.y).lineTo(right, doc.y).stroke();
}

function drawTable(doc: PDFKit.PDFDocument, headers: string[], rows: string[][], widths: number[]): void {
    const startX = doc.x;
    const tableW = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const colW = widths.map((w) => w * tableW);
    const headerY = doc.y;

    doc.fillColor(COLOR_MUTED).fontSize(9).font('Helvetica-Bold');
    let x = startX;
    headers.forEach((h, i) => {
        const align = i === 0 ? 'left' : 'right';
        doc.text(h.toUpperCase(), x, headerY, { width: colW[i], align });
        x += colW[i];
    });
    doc.x = startX;
    doc.y = headerY + 14;
    drawDivider(doc);
    doc.moveDown(0.3);

    rows.forEach((row) => {
        const rowY = doc.y;
        let cx = startX;
        doc.fillColor(COLOR_BODY).fontSize(11).font('Helvetica');
        row.forEach((cell, i) => {
            const align = i === 0 ? 'left' : 'right';
            doc.text(cell, cx, rowY, { width: colW[i], align });
            cx += colW[i];
        });
        doc.x = startX;
        doc.y = rowY + 16;
    });

    doc.moveDown(0.6);
}
